spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.98.251:3306/hx
    username: root
    password: miaoshidahu
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    timeout: 5000
server:
  port: 8090

forest:
  ## ????????/??Forest??/???????? true?
  log-enabled: false
  ## ??/??Forest???????? true?
  log-request: false
  ## ??/??Forest?????????? true?
  log-response-status: false
  ## ??/??Forest?????????? false?
  log-response-content: false
